name: echo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  init-echo:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 10
