name: echo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  init-echo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: sleep 20

  echo:
    runs-on: ubuntu-latest
    needs: init-echo
    steps:
      - name: checkout
        run: sleep 10
