name: echo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - README.md

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: sleep 40
