name: echo2

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed

jobs:
  init-echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo trigger
