name: echo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  init-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
      - name: checkout2
        run: gh pr list --search "label:auto-assign" |  jq '.[].number' | xargs -I@ gh pr edit @ --add-label bug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
