name: echo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo ${{ github.event_name }}
