name: echo2

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: sleep 100
