name: slack

on:
  workflow_run:
    workflows: ["echo", "echo2"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Notify
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          fields: author,ref,pullRequest,commit
          job_name: aaaaaaaa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}